name: 'Setup HDT'
description: 'Setup the HDT C++ library in your environment'
inputs:
  token:
    description: 'GitHub token to use'
    required: true
  hdt-tag:  # id of input
    description: 'Tag of the HDT release to use'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'src/index.js'
