name: 'Setup HDT'
description: 'Setup the HDT C++ library in your environment'
inputs:
  token:
    description: 'GitHub token to use'
    required: true
  hdt-tag:
    description: 'Tag of the HDT release to use'
    required: true
outputs:
  source-path:
    description: 'Absolute path to the HDT source files'
runs:
  using: 'node12'
  main: 'dist/index.js'
