name: 'Setup HDT'
description: 'Setup the HDT C++ library in your environment'
branding:
  icon: 'cpu'  
  color: 'blue'
inputs:
  token:
    description: 'GitHub token to use'
    required: true
  hdt-tag:
    description: 'Tag of the HDT release to use'
    required: true
  source-path:
    description: 'Custom location for storing the HDT source files'
    required: false
    default: './'
outputs:
  source-path:
    description: 'Absolute path to the HDT source files'
runs:
  using: 'node12'
  main: 'dist/index.js'
