name: 🔎 Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Execute action
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          hdt-tag: '1.3.3'
